name: AUTO-CHECKIN
on:
  push:
    branches: [ master ]
    paths-ignore: 
      - 'README.md'
  schedule:
    - cron: 30 21 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: install dependencies
        run: pip install httpx

      - name: checkin
        env:
          CHICKEN_MAIL: ${{ secrets.CHICKEN_MAIL }}
          CHICKEN_PASSWORD: ${{ secrets.CHICKEN_PASSWORD }}
          LOVEZHUOYOU_USER: ${{ secrets.LOVEZHUOYOU_USER }}
          LOVEZHUOYOU_PASSWORD: ${{ secrets.LOVEZHUOYOU_PASSWORD }}
          VGTIME_USER: ${{ secrets.VGTIME_USER }}
          VGTIME_PASSWORD: ${{ secrets.VGTIME_PASSWORD }}
          IYINGDI_USER: ${{ secrets.IYINGDI_USER }}
          IYINGDI_PASSWORD: ${{ secrets.IYINGDI_PASSWORD }}
          SMZDM_SESS_COOKIE: ${{ secrets.SMZDM_SESS_COOKIE }}
          BILIBILI_SESSDATA_COOKIE: ${{ secrets.BILIBILI_SESSDATA_COOKIE }}
          ZHUTIX_USER: ${{ secrets.ZHUTIX_USER }}
          ZHUTIX_PASSWORD: ${{ secrets.ZHUTIX_PASSWORD }}
          PSYDUCK_USER: ${{ secrets.PSYDUCK_USER }}
          PSYDUCK_PASSWORD: ${{ secrets.PSYDUCK_PASSWORD }}
          MIAOTRANSLATION_USER: ${{secrets.MIAOTRANSLATION_USER }}
          MIAOTRANSLATION_PASSWORD: ${{secrets.MIAOTRANSLATION_PASSWORD }}
          SOMERSAULT_USER: ${{ secrets.SOMERSAULT_USER }}
          SOMERSAULT_PASSWORD: ${{ secrets.SOMERSAULT_PASSWORD }}
          PUREFAST_USER: ${{ secrets.PUREFAST_USER }}
          PUREFAST_PASSWORD: ${{ secrets.PUREFAST_PASSWORD }}
        run: python checkin.py
